# Build and Publish Container Images
#
# This workflow builds and publishes three Docker images:
# - GISPy
# - ISIS
# - ASP
#
# Images are tagged using the branch name (for pushes) or using the tag name
# (for tagged commits). When a tag is pushed, the images are also tagged as "latest".
#
# Required repository-level configuration:
# - Variable:
#     - DOCKERHUB_NAMESPACE: Your DockerHub user/organization namespace
# - Secrets:
#     - DOCKERHUB_USERNAME
#     - DOCKERHUB_TOKEN

name: Build and Publish Containers

on:
  push:
    branches:
      - 'test'
      - 'dev'
      - 'latest'
    tags:
      - '*'

jobs:
  gispy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dockerfiles
    env:
      USER_ORG: ${{ vars.DOCKERHUB_NAMESPACE }}
      SERVICE: jupyter-gispy
      REPO: ${{ env.USER_ORG }}/$SERVICE
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build GISPy Image
        run: docker compose build $SERVICE

      - name: Tag Image (Push Event)
        if: ${{ github.event_name == 'push' }}
        run: |
          NEW_IMAGE=$(docker compose config --images $SERVICE)
          docker tag $NEW_IMAGE $REPO:$GITHUB_REF_NAME

      - name: Tag Image as Latest (Tag Event)
        if: ${{ github.ref_type == 'tag' }}
        run: |
          NEW_IMAGE=$(docker compose config --images $SERVICE)
          docker tag $NEW_IMAGE $REPO:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push GISPy Image
        run: |
          docker image ls \
          | tail -n+2 | awk '{print $1":"$2}' \
          | grep "$REPO" \
          | xargs -I'{}' docker push {}

  isis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dockerfiles
    env:
      USER_ORG: ${{ vars.DOCKERHUB_NAMESPACE }}
      SERVICE: jupyter-isis
      REPO: ${{ env.USER_ORG }}/$SERVICE
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Load Environment Variables
        run: |
          source .env
          echo "ISIS_VERSION=${ISIS_VERSION}" >> $GITHUB_ENV

      - name: Build ISIS Image
        run: docker compose build $SERVICE

      - name: Tag Image (Push Event)
        if: ${{ github.event_name == 'push' }}
        run: |
          NEW_IMAGE=$(docker compose config --images $SERVICE)
          docker tag $NEW_IMAGE $REPO:$GITHUB_REF_NAME

      - name: Tag Image as Latest and Versioned (Tag Event)
        if: ${{ github.ref_type == 'tag' }}
        run: |
          NEW_IMAGE=$(docker compose config --images $SERVICE)
          docker tag $NEW_IMAGE $REPO:${ISIS_VERSION}
          docker tag $NEW_IMAGE $REPO:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push ISIS Image
        run: |
          docker image ls \
          | tail -n+2 | awk '{print $1":"$2}' \
          | grep "$REPO" \
          | xargs -I'{}' docker push {}

      - name: List Docker Images
        run: docker image ls -a

  isis-asp:
    needs: isis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dockerfiles
    env:
      USER_ORG: ${{ vars.DOCKERHUB_NAMESPACE }}
      SERVICE: jupyter-isis-asp
      REPO: ${{ env.USER_ORG }}/$SERVICE
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Load Environment Variables
        run: |
          source .env
          echo "ISIS_VERSION=${ISIS_VERSION}" >> $GITHUB_ENV
          echo "ASP_VERSION=${ASP_VERSION}" >> $GITHUB_ENV

      - name: List Docker Images
        run: docker image ls -a

      - name: Build ISIS-ASP Image
        run: |
          ISIS_IMAGE=${{ env.USER_ORG }}/jupyter-isis:${GITHUB_REF_NAME}
          docker compose build --build-arg BASE_IMAGE=${ISIS_IMAGE} $SERVICE

      - name: Tag Image (Push Event)
        if: ${{ github.event_name == 'push' }}
        run: |
          NEW_IMAGE=$(docker compose config --images $SERVICE)
          docker tag $NEW_IMAGE $REPO:$GITHUB_REF_NAME

      - name: Tag Image as Latest and Versioned (Tag Event)
        if: ${{ github.ref_type == 'tag' }}
        run: |
          NEW_IMAGE=$(docker compose config --images $SERVICE)
          docker tag $NEW_IMAGE $REPO:latest
          docker tag $NEW_IMAGE $REPO:${ISIS_VERSION}-${ASP_VERSION}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push ISIS-ASP Image
        run: |
          docker image ls \
          | tail -n+2 | awk '{print $1":"$2}' \
          | grep "$REPO" \
          | xargs -I'{}' docker push {}

      - name: List Docker Images
        run: docker image ls -a

 